language: python
python: 2.7
env:
  - TARGET=test
  - TARGET=coverage.sh
  - TARGET=python-validation.sh
install:
  - pip install --upgrade setuptools==0.9.8
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q -t 3
script: bin/$TARGET
